spring:
  application:
    name: depositary

  datasource:
    url: jdbc:postgresql://depositary:5432/depositary
    username: depositary
    password: password
    driver-class-name: org.postgresql.Driver

    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000

  jpa.properties.hibernate.jdbc.batch_size: 1000
  jpa.properties.hibernate.order_inserts: true
  jpa.properties.hibernate.order_updates: true
  jpa.properties.hibernate.batch_versioned_data: true
  jpa.properties.hibernate.generate_statistics: true

  liquibase:
    change-log: classpath:db/changelog-master.xml

server:
  port: 8030
  error.whitelabel.enabled: false

management:
  endpoints:
    web:
      exposure:
          include: "*"

kafka:
  clusterAddress: ${param.kafka.address}
  topic.executions: executions
  topic.deposits: deposits
  acknowledgement: all # 0 - none; 1 - leader; all - leader and replicas.

depositary:
  executorsNumber: 4

#logging.level.org.springframework: DEBUG
#logging.level.org.apache.kafka: DEBUG
#logging.level.org.hibernate: TRACE
